freeipa_client_version: 4.3.1
server_alias: ipa
server_hostname: ipa.meesho.com
domain: meesho.com
realm: MEESHO.COM
principal_user: admin
principal_user_password: Meesho@405586
directory_manager_password: Meesho@405586